<?php

namespace Sockam\CSPLoggerBundle\Repository;

/**
 * CSPReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CSPReportRepository extends \Doctrine\ORM\EntityRepository
{
}
